version: '3.3'

services:
  claude-code-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-code-dev
    ports:
      - "2222:22"  # SSH接続用
    volumes:
      - ./workspace:/workspace  # ローカルのワークスペースをマウント
      - claude-code-home:/home/developer  # 開発者ホームディレクトリの永続化
    environment:
      # 環境変数でAPI Keyを設定（.envファイルまたは直接設定）
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - claude-dev-network

volumes:
  claude-code-home:

networks:
  claude-dev-network: